### ISSUE TITLE
feature: data url export

### ISSUE THREAD

**Issue by hrgdavor** [hrgdavor/jscadui#88]
Export current script as gzipped data url

 - disable for multifile scripts

**Comment by platypii** [comment]
Not exactly this feature, but related:

I would like to make it so that if you open jscad.app and then hit ctrl-s for save, it pops up a save dialog, and then you can save the file locally, and continue editing it in the browser while updating the saved file any time you hit ctrl-s.

This will make it easy for users to go from experimenting in the browser, to saving their first designs as a .js file.

This idea inspired by the https://excalidraw.com/ workflow.

**Comment by hrgdavor** [comment]
oh, nice, that is a cool idea. I like it. 

if I drag drop a script, browser will allow saving  but with a browser based dialog.

![image](https://github.com/hrgdavor/jscadui/assets/2480762/4de13027-c687-4457-ad05-527cbd5a2891)

I will have to use some other shortcut to render if I do not want to save file. But saving and re-render is actually the perfect choice for CTRL+S.

**Comment by hrgdavor** [comment]
> I would like to make it so that if you open jscad.app and then hit ctrl-s for save,

started this in #92
